version: '3.9'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - database
      - backend_ml
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - taccgpt_network
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - taccgpt_network
    restart: always

  database:
    container_name: database
    image: mongo
    volumes:
      - ./data/database:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - taccgpt_network


  backend:
    container_name: backend
    build: ./backend
    ports:
      - "19990:9990"
    restart: always
    volumes:
      - ./backend/main.py:/etc/backend/main.py:ro
      - ./backend/models.py:/etc/backend/models.py:ro
      - ./backend/database.py:/etc/backend/database.py:ro
    depends_on:
      - database
    networks:
      - taccgpt_network


  frontend:
    container_name: frontend
    build: ./taccgpt_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./taccgpt_frontend/components:/app/components:ro
      - ./taccgpt_frontend/hooks:/app/hooks:ro
      - ./taccgpt_frontend/pages:/app/pages:ro
      - ./taccgpt_frontend/services:/app/services:ro
      - ./taccgpt_frontend/styles:/app/styles:ro
      - ./taccgpt_frontend/types:/app/types:ro
      - ./taccgpt_frontend/utils/app:/app/utils/app:ro
      - ./taccgpt_frontend/utils/data:/app/utils/data:ro
      - ./taccgpt_frontend/utils/server:/app/utils/server:ro
    networks:
      - taccgpt_network

  backend_ml:
    container_name: backend_ml
    build: ./backend_ml
    ports:
      - "19991:9990"
    restart: always
    networks:
      - taccgpt_network
    volumes:
      - ./backend_ml:/etc/TACC_GPT
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
networks:
  taccgpt_network:
    driver: bridge

